apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: sheverev-devops-final-task

images:
  - name: final-task
    newName: vladislavsh3/sheverev-devops-final-task
    newTag: v1.1.0

resources:
- deployment.postgres.yaml
- service.postgres.yaml
